version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  fixtures_test:
    external:
      name: fixtures_test

services:

  explorerdb.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.com
    hostname: explorerdb.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fixtures_test

  explorer.com:
    image: hyperledger/explorer:latest
    container_name: explorer.com
    hostname: explorer.com
    environment:
      - DATABASE_HOST=explorerdb.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWD=admin
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.com:
        condition: service_healthy
    networks:
      - fixtures_test